from pathlib import Path
root=Path(r"D:/Jai Hind Textiles")
files={
"lib/auth.ts": '''import { SignJWT, jwtVerify } from "jose";
import { cookies } from "next/headers";
const secret = new TextEncoder().encode(process.env.JWT_SECRET || "dev-secret");
export async function createToken(payload: { sub: string; role: "user" | "admin"; email: string }) { return new SignJWT(payload).setProtectedHeader({ alg: "HS256" }).setIssuedAt().setExpirationTime("7d").sign(secret); }
export async function currentAdmin() { const c = await cookies(); const token = c.get("jh_admin_token")?.value; if (!token) return null; try { const { payload } = await jwtVerify(token, secret); return payload.role === "admin" ? payload : null; } catch { return null; } }
''',
"models/Admin.ts": 'import { Schema, model, models } from "mongoose"; const adminSchema = new Schema({name:String,email:{type:String,unique:true},passwordHash:String,role:{type:String,default:"admin"}},{timestamps:true}); export const Admin = models.Admin || model("Admin", adminSchema);\n',
"models/Section.ts": 'import { Schema, model, models } from "mongoose"; const sectionSchema = new Schema({name:String,slug:{type:String,unique:true},visible:{type:Boolean,default:true},order:{type:Number,default:0}},{timestamps:true}); export const Section = models.Section || model("Section", sectionSchema);\n',
"models/Product.ts": 'import { Schema, model, models } from "mongoose"; const productSchema = new Schema({name:String,description:String,sectionId:{type:Schema.Types.ObjectId,ref:"Section"},mrp:Number,discount:Number,discountedPrice:Number,stock:Number,sizes:[String],colors:[{name:String,hex:String}],material:String,images:[String],tags:[String],weight:Number,status:{type:String,default:"active"}},{timestamps:true}); export const Product = models.Product || model("Product", productSchema);\n',
"models/Order.ts": 'import { Schema, model, models } from "mongoose"; const orderSchema = new Schema({items:[{productId:{type:Schema.Types.ObjectId,ref:"Product"},productName:String,image:String,size:String,color:String,quantity:Number,price:Number}],customer:{name:String,email:String,phone:String},deliveryType:{type:String,default:"home"},paymentStatus:{type:String,default:"pending"},orderStatus:{type:String,default:"pending"},unreadByAdmin:{type:Boolean,default:true}},{timestamps:true}); export const Order = models.Order || model("Order", orderSchema);\n',
"models/Review.ts": 'import { Schema, model, models } from "mongoose"; const reviewSchema = new Schema({productId:{type:Schema.Types.ObjectId,ref:"Product"},userName:String,rating:Number,comment:String,approved:{type:Boolean,default:false}},{timestamps:true}); export const Review = models.Review || model("Review", reviewSchema);\n',
"app/(user)/layout.tsx": 'export default function L({children}:{children:React.ReactNode}){return <div className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto max-w-6xl p-4 font-semibold">Jaihind Textiles</div></header><main className="mx-auto max-w-6xl p-4">{children}</main></div>}\n',
"app/(user)/page.tsx": 'import { connectDb } from "@/lib/db"; import { Product } from "@/models/Product"; import { Section } from "@/models/Section"; export default async function P(){await connectDb(); const sections=await Section.find({visible:true}).sort({order:1}).lean(); const products=await Product.find({status:"active"}).limit(8).lean(); return <div className="space-y-6"><section className="hero-pattern rounded-3xl p-8"><h1 className="text-4xl font-semibold">Jaihind Textiles</h1><p>Premium textile marketplace for dealers and shoppers.</p></section><section><h2 className="mb-2 text-xl font-semibold">Categories</h2><div className="flex gap-2 overflow-x-auto">{sections.map((s:any)=><span key={s._id} className="rounded-full bg-white px-4 py-2">{s.name}</span>)}</div></section><section><h2 className="mb-2 text-xl font-semibold">Featured Products</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{products.map((p:any)=><a className="product-card rounded-xl bg-white p-2" key={p._id} href={`/products/${p._id}`}><img className="h-32 w-full rounded object-cover" src={p.images?.[0]||"https://picsum.photos/500/500"} alt={p.name}/><p>{p.name}</p></a>)}</div></section></div>}\n',
"app/admin/login/page.tsx": '"use client"; import { useRouter } from "next/navigation"; import { useState } from "react"; export default function A(){const r=useRouter();const [e,sE]=useState(""); async function act(fd:FormData){const res=await fetch("/api/admin/login",{method:"POST",body:fd}); if(!res.ok){sE("Invalid credentials"); return;} r.push("/admin/dashboard");} return <div className="flex min-h-screen items-center justify-center"><form action={act} className="w-full max-w-sm rounded-xl bg-white p-6"><h1 className="text-xl font-semibold">Admin Login</h1><input className="mt-3 w-full border p-2" name="email" type="email" placeholder="Email"/><input className="mt-2 w-full border p-2" name="password" type="password" placeholder="Password"/>{e&&<p className="text-red-600">{e}</p>}<button className="mt-3 w-full bg-[#FF6B00] p-2 text-white">Login</button></form></div>}\n',
"app/admin/layout.tsx": 'import Link from "next/link"; export default function L({children}:{children:React.ReactNode}){return <div><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl gap-4 p-4 text-sm"><Link href="/admin/dashboard">Dashboard</Link><Link href="/admin/sections">Sections</Link><Link href="/admin/products">Products</Link><Link href="/admin/orders">Orders</Link><Link href="/admin/reviews">Reviews</Link></div></header><main className="mx-auto max-w-7xl p-4">{children}</main></div>}\n',
"app/admin/dashboard/page.tsx": 'export default function P(){return <div className="rounded-xl bg-white p-4">Admin dashboard ready. Manage catalog, orders, and reviews from side routes.</div>}\n',
"app/admin/sections/page.tsx": '"use client"; import {useEffect,useState} from "react"; type S={_id:string;name:string;visible:boolean}; export default function P(){const [s,setS]=useState<S[]>([]); async function load(){const r=await fetch("/api/admin/sections");setS(await r.json())} useEffect(()=>{void load()},[]); async function add(fd:FormData){await fetch("/api/admin/sections",{method:"POST",body:fd});await load()} return <div><form action={add} className="mb-3 flex gap-2"><input name="name" className="border p-2" placeholder="Add section"/><button className="bg-[#FF6B00] px-3 text-white">Add</button></form>{s.map(x=><div key={x._id} className="mb-2 rounded bg-white p-2">{x.name}</div>)}</div>}\n',
"app/api/admin/login/route.ts": 'import { NextResponse } from "next/server"; import bcrypt from "bcryptjs"; import { connectDb } from "@/lib/db"; import { Admin } from "@/models/Admin"; import { createToken } from "@/lib/auth"; export async function POST(request:Request){await connectDb(); const f=await request.formData(); const email=String(f.get("email")||"").toLowerCase(); const password=String(f.get("password")||""); const admin=await Admin.findOne({email}); if(!admin || !(await bcrypt.compare(password,admin.passwordHash))) return NextResponse.json({error:"Invalid credentials"},{status:401}); const token=await createToken({sub:admin._id.toString(),role:"admin",email:admin.email}); const res=NextResponse.json({ok:true}); res.cookies.set("jh_admin_token",token,{httpOnly:true,path:"/",sameSite:"lax",secure:process.env.NODE_ENV==="production"}); return res;}\n',
"app/api/admin/sections/route.ts": 'import { NextResponse } from "next/server"; import { connectDb } from "@/lib/db"; import { Section } from "@/models/Section"; import { currentAdmin } from "@/lib/auth"; const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-"); export async function GET(){await connectDb(); return NextResponse.json(await Section.find().sort({order:1}).lean());} export async function POST(request:Request){if(!(await currentAdmin())) return NextResponse.json({error:"Unauthorized"},{status:401}); await connectDb(); const f=await request.formData(); const name=String(f.get("name")||""); if(!name) return NextResponse.json({error:"Name required"},{status:400}); const order=await Section.countDocuments(); await Section.create({name,slug:slug(name),visible:true,order}); return NextResponse.json({ok:true});}\n',
"app/api/admin/products/route.ts": 'import { NextResponse } from "next/server"; import { connectDb } from "@/lib/db"; import { Product } from "@/models/Product"; export async function GET(){await connectDb(); return NextResponse.json(await Product.find().sort({createdAt:-1}).lean());}\n',
"app/api/admin/orders/route.ts": 'import { NextResponse } from "next/server"; import { connectDb } from "@/lib/db"; import { Order } from "@/models/Order"; import { currentAdmin } from "@/lib/auth"; export async function GET(){if(!(await currentAdmin())) return NextResponse.json({error:"Unauthorized"},{status:401}); await connectDb(); return NextResponse.json(await Order.find().sort({createdAt:-1}).lean());}\n',
"app/api/admin/reviews/route.ts": 'import { NextResponse } from "next/server"; import { connectDb } from "@/lib/db"; import { Review } from "@/models/Review"; import { currentAdmin } from "@/lib/auth"; export async function GET(){if(!(await currentAdmin())) return NextResponse.json({error:"Unauthorized"},{status:401}); await connectDb(); return NextResponse.json(await Review.find().sort({createdAt:-1}).lean());}\n',
"middleware.ts": 'import { NextResponse } from "next/server"; import type { NextRequest } from "next/server"; import { jwtVerify } from "jose"; const secret=new TextEncoder().encode(process.env.JWT_SECRET||"dev-secret"); async function isAdmin(token?:string){if(!token)return false; try{const {payload}=await jwtVerify(token,secret); return payload.role==="admin";}catch{return false;}} export async function middleware(request:NextRequest){const p=request.nextUrl.pathname; if(p.startsWith("/admin")&&p!=="/admin/login"){if(!(await isAdmin(request.cookies.get("jh_admin_token")?.value))) return NextResponse.redirect(new URL("/admin/login",request.url));} return NextResponse.next();} export const config={matcher:["/admin/:path*"]};\n',
"scripts/seed.ts": 'import bcrypt from "bcryptjs"; import { connectDb } from "@/lib/db"; import { Admin } from "@/models/Admin"; import { Section } from "@/models/Section"; import { Product } from "@/models/Product"; async function run(){await connectDb(); const ph=await bcrypt.hash("Admin@123",10); await Admin.updateOne({email:"admin@jaihindtextiles.com"},{$set:{name:"Admin",email:"admin@jaihindtextiles.com",passwordHash:ph,role:"admin"}},{upsert:true}); const names=["Sarees","Dress Materials","Kurtis","Blouses","Kids Wear"]; const sections=[] as any[]; for(let i=0;i<names.length;i++){const n=names[i]; const s=await Section.findOneAndUpdate({slug:n.toLowerCase().replace(/[^a-z0-9]+/g,"-")},{$set:{name:n,slug:n.toLowerCase().replace(/[^a-z0-9]+/g,"-"),order:i,visible:true}},{upsert:true,new:true}); sections.push(s);} await Product.deleteMany({}); for(let i=1;i<=10;i++){const mrp=500+i*90; const discount=i%2?10:18; await Product.create({name:`Sample Product ${i}`,description:`Textile item ${i}`,sectionId:sections[i%sections.length]._id,mrp,discount,discountedPrice:mrp-mrp*discount/100,stock:20+i,sizes:["S","M","L","XL","Free Size"],colors:[{name:"Saffron",hex:"#FF6B00"}],material:"Cotton",images:[`https://picsum.photos/seed/jh-${i}/600/600`],tags:[i%2?"new arrival":"trending"],weight:0.4,status:"active"});} console.log("Seed completed"); process.exit(0);} run().catch(e=>{console.error(e);process.exit(1)});\n',
".env.example": 'MONGODB_URI=mongodb://127.0.0.1:27017/jaihind\nJWT_SECRET=change-me\nCLOUDINARY_CLOUD_NAME=\nCLOUDINARY_API_KEY=\nCLOUDINARY_API_SECRET=\nRAZORPAY_KEY_ID=\nRAZORPAY_KEY_SECRET=\nSMTP_HOST=\nSMTP_PORT=587\nSMTP_USER=\nSMTP_PASS=\n',
"README.md": '# Jaihind Textiles\n\nNext.js + MongoDB e-commerce scaffold with separate admin portal.\n\n## Setup\n- `npm install`\n- Copy `.env.example` to `.env.local`\n- Set `MONGODB_URI` and `JWT_SECRET`\n- `npm run seed`\n- `npm run dev`\n\n## Admin\n- `/admin/login`\n- Email: `admin@jaihindtextiles.com`\n- Password: `Admin@123`\n'
}
for rel,content in files.items():
    p=root/rel
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(content,encoding="utf-8")
